
CREATE TABLE IF NOT EXISTS users (
	id 			BIGINT GENERATED BY DEFAULT AS IDENTITY,
	username 			VARCHAR(250) 														NOT NULL,
	password 			VARCHAR(250) 														NOT NULL,
	email 				VARCHAR(40) 				CHECK (email <> '')						NOT NULL,

	CONSTRAINT pk_users PRIMARY KEY (id),
	CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS roles (
	id 			BIGINT GENERATED BY DEFAULT AS IDENTITY,
	name 		VARCHAR(250) 																NOT NULL,

	CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users_roles (
	user_id				BIGINT																NOT NULL,
    role_id				INTEGER																NOT NULL,

	CONSTRAINT pk_users_roles PRIMARY KEY (user_id, role_id),
	CONSTRAINT pk_users_roles_users FOREIGN KEY (user_id) REFERENCES users (id),
	CONSTRAINT pk_users_roles_roles FOREIGN KEY (role_id) REFERENCES roles (id)
);

